blank_issues_enabled: true
contact_links:
  - name: Online Web Demo (rvemu-web)
    url: https://github.com/here-emulator/here-web/issues
    about: The WebAssembly version of HERE emulator in your browser.
